### ISSUE TITLE
Latest release on HACS doens't have the postcode lookup

### ISSUE THREAD

**Issue by codiourso** [TomBrien/cardiffwaste-ha#16]
As another Cardiffian, this is just the addon I needed - however the lookup on the released version is still UDPRN not postcode.  The changes appear to be in main, but not on a release yet.

**Comment by TomBrien** [comment]
Hi @codiourso sorry I was waiting for the release on HACS default branch repo before doing the release. That happened yesterday but then the weekend got busy. I'll just cut a release now

**Comment by TomBrien** [comment]
Done. You may need to either wait for HACS to check for the update or force the check by using the three dots on the integration in HACS and "Update Information"

**Comment by TomBrien** [comment]
P.s. thanks for opening the issue and do let me k ow if you find anything else or have ideas. This is hugely untested still

**Comment by codiourso** [comment]
So far, it's working fine - got the right days for my collections, which is pretty much all it needs!

Thanks for the updated release, I'll update that and let you know if I have any problems.
