### ISSUE TITLE
Error: Config flow could not be loaded

### ISSUE THREAD

**Issue by mattl1598** [TomBrien/cardiffwaste-ha#17]
Trying to add this integration as per the instructions in the README but I repeatedly get the error "Config flow could not be loaded". Tried restarting the server and trying again but it didn't help

```
Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 18:09:02 (1 occurrences)
Last logged: 18:09:02

Error occurred loading configuration flow for integration cardiffwaste: cannot import name 'Platform' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

**Comment by TomBrien** [comment]
Hi. What version of Home Assistant  core are you running please? You can follow this link to check [![Open your Home Assistant instance and show your Home Assistant version information.](https://my.home-assistant.io/badges/info.svg)](https://my.home-assistant.io/redirect/info/)

**Comment by mattl1598** [comment]
Currently running core-2021.11.5

**Comment by TomBrien** [comment]
Opps looks like I got the minimum supported version of HA out by one. Are you able to upgrade to at least 2021.12. That should fix the issue

**Comment by mattl1598** [comment]
yes, updating home assistant core worked.
I ended up updating to 2022.2 as that was the latest version available
